import { useEffect, useState, type ReactNode } from 'react'
import { Folder, Settings, Star, X } from 'lucide-react'
import type { AgentMode, CodexSettings, Workspace } from '../../types'
import { errorMessage, statusText } from '../../shared/format'

export function SettingsDialog({ value, status, workspaces, onClose, onSave, onOnboarding }: { value: CodexSettings; status: string; workspaces: Workspace[]; onClose(): void; onSave(value: CodexSettings): void; onOnboarding(): void }) {
  const [form, setForm] = useState(value)
  const [diagnostic, setDiagnostic] = useState('Carregando diagnóstico…')
  useEffect(() => { void window.nocturne.codex.diagnostics().then((item) => setDiagnostic(`PID: ${item.pid ?? '—'} · ${item.executable}\nÚltima falha: ${item.lastFailure || 'nenhuma'}`)).catch((error) => setDiagnostic(errorMessage(error))) }, [])
  const copyDiagnostic = async () => { const content = await window.nocturne.diagnostics.copy(); await navigator.clipboard.writeText(content) }
  return <div className="modal-backdrop" onMouseDown={onClose}><div className="settings-dialog beta-settings" onMouseDown={(event) => event.stopPropagation()}><div className="modal-title"><Settings size={17}/><strong>Configurações</strong><button onClick={onClose}><X size={16}/></button></div><div className="settings-scroll">
    <SettingsSection title="Codex"><div className="codex-info"><span className={`status-dot ${status}`}/><div><strong>{statusText(status)}</strong><small>{value.codexVersion || 'Versão indisponível'} · {value.authenticated ? 'Autenticado' : 'Login necessário'}</small></div></div><label>Executável<input value={form.codexPath || ''} onChange={(event) => setForm({ ...form, codexPath: event.target.value })} placeholder="codex ou caminho absoluto"/></label><label>Modelo<input value={form.model} onChange={(event) => setForm({ ...form, model: event.target.value })} placeholder="Padrão do Codex"/></label><div className="settings-columns"><label>Sandbox<select value={form.sandbox} onChange={(event) => setForm({ ...form, sandbox: event.target.value as CodexSettings['sandbox'] })}><option value="read-only">Somente leitura</option><option value="workspace-write">Escrita no workspace</option></select></label><label>Aprovações<select value={form.approvalPolicy} onChange={(event) => setForm({ ...form, approvalPolicy: event.target.value as CodexSettings['approvalPolicy'] })}><option value="untrusted">Não confiáveis</option><option value="on-request">Quando solicitado</option><option value="never">Sempre proteger riscos</option></select></label></div></SettingsSection>
    <SettingsSection title="Workspace"><div className="settings-workspaces">{workspaces.slice(0, 6).map((workspace) => <div key={workspace.path}><Folder size={13}/><span><strong>{workspace.name}</strong><small>{workspace.path}</small></span>{workspace.favorite && <Star size={12} fill="currentColor"/>}</div>)}{!workspaces.length && <p>Nenhum workspace recente.</p>}</div></SettingsSection>
    <SettingsSection title="Aplicação"><div className="settings-columns"><label>Tema<select value={form.theme || 'dark'} onChange={(event) => setForm({ ...form, theme: event.target.value as CodexSettings['theme'] })}><option value="dark">Nocturne escuro</option><option value="system">Seguir sistema</option></select></label><label>Modo padrão<select value={form.defaultAgentMode || 'review'} onChange={(event) => setForm({ ...form, defaultAgentMode: event.target.value as AgentMode })}><option value="review">Review</option><option value="build">Build</option><option value="docs">Docs</option></select></label></div><label className="check-label"><input type="checkbox" checked={Boolean(form.diagnosticMode)} onChange={(event) => setForm({ ...form, diagnosticMode: event.target.checked })}/>Ativar logs detalhados</label><button className="secondary-setting" onClick={onOnboarding}>Reabrir primeira execução</button></SettingsSection>
    <SettingsSection title="Diagnóstico"><pre className="diagnostic-summary">{diagnostic}</pre><div className="diagnostic-actions"><button onClick={() => window.nocturne.codex.restart().then(() => setDiagnostic('Codex reiniciado com sucesso.')).catch((error) => setDiagnostic(errorMessage(error)))}>Reiniciar Codex</button><button onClick={() => window.nocturne.diagnostics.openLogs()}>Abrir logs</button><button onClick={copyDiagnostic}>Copiar informações</button><button onClick={() => window.nocturne.data.export()}>Exportar dados</button></div></SettingsSection>
  </div><div className="modal-actions"><button onClick={onClose}>Cancelar</button><button className="primary" onClick={() => onSave(form)}>Salvar</button></div></div></div>
}
function SettingsSection({ title, children }: { title: string; children: ReactNode }) { return <section className="settings-section"><h3>{title}</h3>{children}</section> }

