export const IPC_CHANNELS = {
  workspace: { select: 'workspace:select', validate: 'workspace:validate', list: 'workspaces:list', remove: 'workspaces:remove', favorite: 'workspaces:favorite', openTool: 'workspace:openTool' },
  conversations: { list: 'conversations:list', page: 'conversations:page', create: 'conversations:create', messages: 'conversations:messages', messagePage: 'conversations:messagePage', delete: 'conversations:delete' },
  codex: { start: 'codex:start', restart: 'codex:restart', diagnostics: 'codex:diagnostics', send: 'codex:send', resume: 'codex:resume', interrupt: 'codex:interrupt', saveAssistant: 'codex:save-assistant', approve: 'codex:approve', event: 'codex:event', status: 'codex:status' },
  files: { attach: 'files:attach', open: 'files:open', preview: 'files:preview' },
  memory: { get: 'memory:get', set: 'memory:set' },
  brain: { page: 'brain:page', create: 'brain:create', update: 'brain:update', delete: 'brain:delete', extract: 'brain:extract' },
  artifacts: { list: 'artifacts:list', page: 'artifacts:page', delete: 'artifacts:delete' },
  suggestions: { list: 'suggestions:list', page: 'suggestions:page', create: 'suggestions:create', status: 'suggestions:status' },
  data: { export: 'data:export', import: 'data:import' },
  diagnostics: { openLogs: 'diagnostics:openLogs', copy: 'diagnostics:copy', rendererError: 'diagnostics:rendererError', rendererStats: 'diagnostics:rendererStats' },
  settings: { get: 'settings:get', check: 'settings:check', set: 'settings:set' },
  providers: { list: 'providers:list', create: 'providers:create', update: 'providers:update', remove: 'providers:remove', testConnection: 'providers:testConnection' },
  git: { status: 'git:status', commit: 'git:commit' },
  documents: { saveMarkdown: 'documents:saveMarkdown', export: 'documents:export' },
  clipboard: { readText: 'clipboard:readText', writeText: 'clipboard:writeText' },
} as const
